"""INIT

Revision ID: 11c935d61c02
Revises: 
Create Date: 2026-01-26 08:46:00.734301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11c935d61c02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cor_id_auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cor_id', sa.String(length=250), nullable=True),
    sa.Column('session_token', sa.String(length=36), nullable=False),
    sa.Column('app_id', sa.String(length=250), nullable=True),
    sa.Column('device_id', sa.String(length=250), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'TIMEOUT', name='authsessionstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cor_id_auth_sessions_token', 'cor_id_auth_sessions', ['session_token'], unique=False)
    op.create_index(op.f('ix_cor_id_auth_sessions_cor_id'), 'cor_id_auth_sessions', ['cor_id'], unique=False)
    op.create_index(op.f('ix_cor_id_auth_sessions_email'), 'cor_id_auth_sessions', ['email'], unique=False)
    op.create_index(op.f('ix_cor_id_auth_sessions_session_token'), 'cor_id_auth_sessions', ['session_token'], unique=True)
    op.create_table('energetic_objects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='Имя/название объекта'),
    sa.Column('model_name', sa.String(), nullable=True, comment='Модель устройства/инвертора'),
    sa.Column('description', sa.String(), nullable=True, comment='Описание объекта'),
    sa.Column('protocol', sa.String(), nullable=True, comment='Протокол связи'),
    sa.Column('vendor', sa.String(), nullable=True, comment='Производитель/вендор инвертора'),
    sa.Column('ip_address', sa.String(), nullable=True, comment='IP-адрес объекта'),
    sa.Column('port', sa.Integer(), nullable=True, comment='Порт объекта'),
    sa.Column('inverter_login', sa.String(), nullable=True, comment='Логин для доступа к инвертору'),
    sa.Column('inverter_password', sa.String(), nullable=True, comment='Пароль для доступа к инвертору'),
    sa.Column('timezone', sa.String(), server_default='Europe/Kiev', nullable=True, comment='Часовой пояс объекта (например: Europe/Kiev)'),
    sa.Column('modbus_config_file', sa.String(), nullable=True, comment='Имя файла конфигурации Modbus регистров (например: victron_cerbo_gx.json)'),
    sa.Column('cor_bridges', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True, comment='Список доступных device_id энергетических устройств, связанных с объектом'),
    sa.Column('telegram_bot_token', sa.String(), nullable=True, comment='Telegram bot token для этого объекта (опционально, если None - используется глобальный)'),
    sa.Column('telegram_bot_name', sa.String(), nullable=True, comment='Имя Telegram бота (опционально, для информации)'),
    sa.Column('telegram_chat_ids', sa.String(), nullable=True, comment='Список Telegram chat IDs через запятую для уведомлений'),
    sa.Column('telegram_battery_threshold', sa.Integer(), nullable=True, comment='Порог низкого заряда батареи для уведомлений (%)'),
    sa.Column('telegram_cooldown_minutes', sa.Integer(), nullable=True, comment='Интервал между повторными уведомлениями (минуты)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Активен ли фоновый опрос'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cor_id', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('backup_email', sa.String(length=250), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('last_password_change', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('recovery_code', sa.LargeBinary(), nullable=True),
    sa.Column('unique_cipher_key', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_sex', sa.String(length=10), nullable=True),
    sa.Column('birth', sa.Integer(), nullable=True),
    sa.Column('user_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backup_email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_index')
    )
    op.create_index('idx_users_cor_id', 'users', ['cor_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_cor_id'), 'users', ['cor_id'], unique=False)
    op.create_index('users_cor_id_key', 'users', ['cor_id'], unique=True)
    op.create_table('verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('verification_code', sa.Integer(), nullable=True),
    sa.Column('email_confirmation', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_verification_email', 'verification', ['email'], unique=False)
    op.create_table('websocket_broadcast_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False, comment='Имя задачи'),
    sa.Column('session_id', sa.String(), nullable=False, comment='Session ID устройства'),
    sa.Column('command_type', sa.String(), nullable=False, comment='Тип команды: pi30 | modbus_read'),
    sa.Column('command_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Полезная нагрузка команды (для pi30: {pi30: hex}, для modbus_read: {hex_data: ...})'),
    sa.Column('interval_seconds', sa.Float(), nullable=False, comment='Интервал отправки команды в секундах'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли задача рассылки'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True, comment='Кто создал задачу (user_id или admin)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websocket_broadcast_tasks_session_id'), 'websocket_broadcast_tasks', ['session_id'], unique=False)
    op.create_table('cerbo_measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('energetic_object_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False, comment='Дата и время измерения'),
    sa.Column('object_name', sa.String(), nullable=True),
    sa.Column('general_battery_power', sa.Float(), nullable=False),
    sa.Column('inverter_total_ac_output', sa.Float(), nullable=False),
    sa.Column('ess_total_input_power', sa.Float(), nullable=False),
    sa.Column('solar_total_pv_power', sa.Float(), nullable=False),
    sa.Column('soc', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['energetic_object_id'], ['energetic_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cerbo_measurements_energetic_object_id'), 'cerbo_measurements', ['energetic_object_id'], unique=False)
    op.create_index(op.f('ix_cerbo_measurements_object_name'), 'cerbo_measurements', ['object_name'], unique=False)
    op.create_table('device_polling_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('energetic_object_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False, comment='Тип задачи: cerbo_collection | schedule_check | modbus_registers | custom_command'),
    sa.Column('command_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Конфигурация команд в JSON формате (какие регистры читать, параметры команды)'),
    sa.Column('interval_seconds', sa.Float(), nullable=False, comment='Интервал опроса в секундах'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли задача опроса'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['energetic_object_id'], ['energetic_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_polling_tasks_energetic_object_id'), 'device_polling_tasks', ['energetic_object_id'], unique=False)
    op.create_table('energetic_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True, comment='Модель устройства'),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('owner_cor_id', sa.String(length=250), nullable=False),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_cor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energetic_devices_device_id'), 'energetic_devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_energetic_devices_owner_cor_id'), 'energetic_devices', ['owner_cor_id'], unique=False)
    op.create_table('energetic_schedule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('energetic_object_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False, comment='Время начала работы режима (ЧЧ:ММ)'),
    sa.Column('duration', sa.Interval(), nullable=False, comment='Продолжительность режима'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='Время окончания работы режима'),
    sa.Column('grid_feed_w', sa.Integer(), nullable=False, comment='Отдача в сеть (Вт)'),
    sa.Column('battery_level_percent', sa.Integer(), nullable=False, comment='Целевой уровень батареи (%)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_manual_mode', sa.Boolean(), nullable=False),
    sa.Column('charge_battery_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['energetic_object_id'], ['energetic_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energetic_schedule_energetic_object_id'), 'energetic_schedule', ['energetic_object_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_surname', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_first_name', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_middle_name', sa.LargeBinary(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('car_brand', sa.String(length=100), nullable=True),
    sa.Column('engine_type', sa.String(length=50), nullable=True),
    sa.Column('fuel_tank_volume', sa.Integer(), nullable=True),
    sa.Column('photo_data', sa.LargeBinary(), nullable=True),
    sa.Column('photo_file_type', sa.String(), nullable=True),
    sa.Column('change_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('token', sa.String(length=250), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_invitations_email'), 'user_invitations', ['email'], unique=False)
    op.create_index('ix_user_invitations_email_not_used', 'user_invitations', ['email', 'is_used'], unique=False)
    op.create_index(op.f('ix_user_invitations_token'), 'user_invitations', ['token'], unique=True)
    op.create_index('ix_user_invitations_token_not_used', 'user_invitations', ['token', 'is_used'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_type', sa.String(length=250), nullable=True),
    sa.Column('device_info', sa.String(length=250), nullable=True),
    sa.Column('app_id', sa.String(length=250), nullable=True),
    sa.Column('device_id', sa.String(length=250), nullable=True),
    sa.Column('ip_address', sa.String(length=250), nullable=True),
    sa.Column('device_os', sa.String(length=250), nullable=True),
    sa.Column('jti', sa.String(), nullable=True, comment='JTI последнего Access токена, выданного для этой сессии'),
    sa.Column('refresh_token', sa.LargeBinary(), nullable=True),
    sa.Column('access_token', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_table('energetic_device_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('granting_user_cor_id', sa.String(length=36), nullable=True),
    sa.Column('accessing_user_cor_id', sa.String(length=36), nullable=False),
    sa.Column('access_level', sa.Enum('READ', 'READ_WRITE', 'SHARE', name='accesslevel'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accessing_user_cor_id'], ['users.cor_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['energetic_devices.id'], ),
    sa.ForeignKeyConstraint(['granting_user_cor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energetic_device_access')
    op.drop_index('idx_user_sessions_user_id', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_roles')
    op.drop_index('ix_user_invitations_token_not_used', table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_token'), table_name='user_invitations')
    op.drop_index('ix_user_invitations_email_not_used', table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_email'), table_name='user_invitations')
    op.drop_table('user_invitations')
    op.drop_table('role_permissions')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_energetic_schedule_energetic_object_id'), table_name='energetic_schedule')
    op.drop_table('energetic_schedule')
    op.drop_index(op.f('ix_energetic_devices_owner_cor_id'), table_name='energetic_devices')
    op.drop_index(op.f('ix_energetic_devices_device_id'), table_name='energetic_devices')
    op.drop_table('energetic_devices')
    op.drop_index(op.f('ix_device_polling_tasks_energetic_object_id'), table_name='device_polling_tasks')
    op.drop_table('device_polling_tasks')
    op.drop_index(op.f('ix_cerbo_measurements_object_name'), table_name='cerbo_measurements')
    op.drop_index(op.f('ix_cerbo_measurements_energetic_object_id'), table_name='cerbo_measurements')
    op.drop_table('cerbo_measurements')
    op.drop_index(op.f('ix_websocket_broadcast_tasks_session_id'), table_name='websocket_broadcast_tasks')
    op.drop_table('websocket_broadcast_tasks')
    op.drop_index('idx_verification_email', table_name='verification')
    op.drop_table('verification')
    op.drop_index('users_cor_id_key', table_name='users')
    op.drop_index(op.f('ix_users_cor_id'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_cor_id', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('energetic_objects')
    op.drop_index(op.f('ix_cor_id_auth_sessions_session_token'), table_name='cor_id_auth_sessions')
    op.drop_index(op.f('ix_cor_id_auth_sessions_email'), table_name='cor_id_auth_sessions')
    op.drop_index(op.f('ix_cor_id_auth_sessions_cor_id'), table_name='cor_id_auth_sessions')
    op.drop_index('idx_cor_id_auth_sessions_token', table_name='cor_id_auth_sessions')
    op.drop_table('cor_id_auth_sessions')
    # ### end Alembic commands ###
